#
# Makefile for UNIX (System V)
#

LIBS = ../regexp/regexp.a
LDFLAGS=

CFLAGS = -I../regexp -O

MACH=	unix.o

OBJ=	main.o edit.o linefunc.o normal.o cmdline.o hexchars.o \
	misccmds.o help.o ptrfunc.o search.o alloc.o \
	mark.o screen.o fileio.o param.o $(MACH)

all : stevie

stevie : $(OBJ)
	$(CC) $(OBJ) $(LIBS) -o stevie

clean :
	rm $(OBJ)
