#define     SPECIAL_KEYS_CHAR	    0x00
#define     CTRL_B_CHAR 	    0x02
#define     BKSP_CHAR		    0x08
#define     TAB_CHAR		    0x09
#define     CRETURN_CHAR	    0x0D
#define     CTRL_N_CHAR 	    0x0E
#define     CTRL_Y_CHAR 	    0x19
#define     SHIFT_END_CHAR	    0x31
#define     SHIFT_DOWN_CHAR	    0x32
#define     SHIFT_LEFT_CHAR	    0x34
#define     SHIFT_RIGHT_CHAR	    0x36
#define     SHIFT_HOME_CHAR	    0x37
#define     SHIFT_UP_CHAR	    0x38
#define     ARROW_CHAR		    0xE0

#define     F9_SCAN		    0x43
#define     F10_SCAN		    0x44
#define     HOME_SCAN		    0x47
#define     UP_SCAN		    0x48
#define     PGUP_SCAN		    0x49
#define     LEFT_SCAN		    0x4B
#define     RIGHT_SCAN		    0x4D
#define     END_SCAN		    0x4F
#define     DOWN_SCAN		    0x50
#define     PGDN_SCAN		    0x51
#define     DEL_SCAN		    0x53
#define     CTRL_END_SCAN	    0x75
#define     CTRL_PGDN_SCAN	    0x76
#define     CTRL_HOME_SCAN	    0x77
#define     CTRL_PGUP_SCAN	    0x84
