copy Y1IMP.C a:
copy Y2IMP.C a:
copy Y3IMP.C a:
copy Y4IMP.C a:
copy YARYFL.1C a:
copy YCEMTY.1C a:
copy YCHCPY.1C a:
copy YCLSUR.1C a:
copy YCPFIR.1C a:
copy YCPRES.1C a:
copy YERROR.C a:
copy YERROR.1C a:
copy YFLSET.1C a:
copy YMAIN.1C a:
copy YOTHRS.1C a:
copy YPRLOK.1C a:
copy YPTITM.1C a:
copy YSMNAM.1C a:
copy YSTAGN.1C a:
copy YSTATE.1C a:
copy YSTUNI.1C a:
copy YSUMRY.1C a:
copy YWRITM.1C a:
copy YCHFND.2C a:
copy YCPACT.2C a:
copy YCPUNI.2C a:
copy YCPYCD.2C a:
copy YCSTSH.2C a:
copy YDEFIN.2C a:
copy YDFOUT.2C a:
copy YFDTYP.2C a:
copy YFNACT.2C a:
copy YGTTOK.2C a:
copy YSETUP.2C a:
copy YSKPCM.2C a:
copy YAPACK.3C a:
copy YG2GEN.3C a:
copy YG2OUT.3C a:
copy YHDPRD.3C a:
copy YOUTPT.3C a:
copy YPRCFT.3C a:
copy YWARRY.3C a:
copy YWRACT.3C a:
copy YWSTAT.3C a:
copy YAOPUT.4C a:
copy YAROUT.4C a:
copy YCLOPT.4C a:
copy YGIN.4C a:
copy YGTNM.4C a:
copy YNXTI.4C a:
copy YOSMRY.4C a:
copy YSTIN.4C a:
copy Y1.H a:
copy Y2.H a:
copy Y3.H a:
copy Y4.H a:
copy DTXTRN.H a:
copy SYSTEM.H a:
copy BACKUP.BAT a:
copy LIB1.BAT a:
copy LIB2.BAT a:
copy LIB3.BAT a:
copy LIB4.BAT a:
copy COMPILE.BAT a:
copy BUILD.BAT a:
copy YYPARS.C a:
copy YYLESS.C a:
copy YYWRAP.C a:
copy EX613.Y a:
copy CPY.Y a:
copy SIMPL.Y a:
copy SPIKE.Y a:
copy LANDY.LXI a:
copy LANDY.Y a:
copy YACC.DOC a:
copy YACC.INF a:
copy YACC.EXE a:
