copy LEX.H a:
copy LEXLEX.H a:
copy STDIO.H a:
copy SYSTEM.H a:
copy YTAB.H a:
copy BASE.C a:
copy COMMEN.C a:
copy DFA.C a:
copy ECLOSU.C a:
copy GETTOK.C a:
copy IMPURE.C a:
copy INTEG.C a:
copy LEX.C a:
copy LEXCHA.C a:
copy LEXECH.C a:
copy LEXERR.C a:
copy LEXGET.C a:
copy LEXLEN.C a:
copy LEXPEE.C a:
copy LEXSRT.C a:
copy LEXSWI.C a:
copy LLSAVE.C a:
copy LMOVB.C a:
copy LMOVI.C a:
copy MAPCH.C a:
copy MIN.C a:
copy OUT2.C a:
copy OUT1.C a:
copy TOKEN.C a:
copy YTAB.C a:
copy YYLEX.C a:
copy LEXLIB.S a:
copy LEX.EXE a:
copy LEX.Y a:
copy LEX.MEM a:
copy LEX.INF a:
copy LEX.HLP a:
copy BUILD.BAT a:
copy FINDC.BAT a:
copy COMPILE.BAT a:
copy MAKELIB.BAT a:
copy BACKUP.BAT a:
copy ABC.LXI a:
copy BCPL.LXI a:
copy BTOB.LXI a:
copy CAP.LXI a:
copy CLEX.LXI a:
copy CTOC.LXI a:
copy HWORD.LXI a:
copy LANDY.LXI a:
copy WORD.LXI a:
