find %1 base.c
find %1 commen.c
find %1 dfa.c
find %1 eclosu.c
find %1 gettok.c
find %1 impure.c
find %1 integ.c
find %1 lex.c
find %1 lexcha.c
find %1 lexech.c
find %1 lexerr.c
find %1 lexget.c
find %1 lexlen.c
find %1 lexpee.c
find %1 lexsrt.c
find %1 lexswi.c
find %1 llsave.c
find %1 lmovb.c
find %1 lmovi.c
find %1 mapch.c
find %1 min.c
find %1 out1.c
find %1 out2.c
find %1 token.c
find %1 ytab.c
find %1 yylex.c
