LIST COMPILER.DOC

REM EXAMPLE PROGRAM FOR CHAPTER 1
LIST FIRSTEX.C

REM EXAMPLE PROGRAMS FOR CHAPTER 2
LIST TRIVIAL.C
LIST WRTSOME.C
LIST WRTMORE.C
LIST ONEINT.C
LIST COMMENTS.C
LIST GOODFORM.C
LIST UGLYFORM.C

REM EXAMPLE PROGRAMS FOR CHAPTER 3
LIST WHILE.C
LIST DOWHILE.C
LIST FORLOOP.C
LIST IFELSE.C
LIST BREAKCON.C
LIST SWITCH.C
LIST GOTOEX.C
LIST TEMPCONV.C
LIST DUMBCONV.C

REM EXAMPLE PROGRAMS FOR CHAPTER 4
LIST INTASIGN.C
LIST MORTYPES.C
LIST LOTTYPES.C
LIST COMPARES.C
LIST CRYPTIC.C

REM EXAMPLE PROGRAMS FOR CHAPTER 5
LIST SUMSQRES.C
LIST SQUARES.C
LIST FLOATSQ.C
LIST SCOPE.C
LIST RECURSON.C
LIST BACKWARD.C
LIST FLOATSQ2.C

REM EXAMPLE PROGRAMS FOR CHAPTER 6
LIST DEFINE.C
LIST MACRO.C
LIST ENUM.C

REM EXAMPLE PROGRAMS FOR CHAPTER 7
LIST CHRSTRG.C
LIST STRINGS.C
LIST INTARRAY.C
LIST BIGARRAY.C
LIST PASSBACK.C
LIST MULTIARY.C

REM EXAMPLE PROGRAMS FOR CHAPTER 8
LIST POINTER.C
LIST POINTER2.C
LIST TWOWAY.C

REM EXAMPLE PROGRAMS FOR CHAPTER 9
LIST SIMPLEIO.C
LIST SINGLEIO.C
LIST BETTERIN.C
LIST INTIN.C
LIST STRINGIN.C
LIST INMEM.C
LIST SPECIAL.C

REM EXAMPLE PROGRAMS FOR CHAPTER 10
LIST FORMOUT.C
LIST CHAROUT.C
LIST READCHAR.C
LIST READTEXT.C
LIST READGOOD.C
LIST READLINE.C
LIST ANYFILE.C
LIST PRINTDAT.C

REM EXAMPLE PROGRAMS FOR CHAPTER 11
LIST STRUCT1.C
LIST STRUCT2.C
LIST STRUCT3.C
LIST NESTED.C
LIST UNION1.C
LIST UNION2.C
LIST BITFIELD.C

REM EXAMPLE PROGRAMS FOR CHAPTER 12
LIST DYNLIST.C
LIST BIGDYNL.C
LIST DYNLINK.C

REM EXAMPLE PROGRAMS FOR CHAPTER 13
LIST UPLOW.C
LIST CHARCLAS.C
LIST BITOPS.C
LIST SHIFTER.C

REM EXAMPLE PROGRAMS FOR CHAPTER 14
REM DOS CALL EXAMPLE PROGRAM
LIST DOSEX.C

REM COMMAND LINE INPUT EXAMPLE
LIST WHATNEXT.C
LIST TEST.BAT

REM LIST TEXT WITH LINE NUMBERS
LIST LIST.C
LIST LISTF.C
LIST LIST.PRJ

REM THE VISUAL CALCULATOR
LIST VC.DOC
LIST DEFIN.H
LIST STRUCT.DEF
LIST VC.C
LIST DATA.C
LIST FILE.C
LIST VIDEO.C
LIST VC.PRJ

