C
C     INTERFACE ROUTINE FROM DEC TO PC FOR GETTING TIME
C
      FUNCTION SECNDS(X)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C     RETURN CURRENT TIME - MIDNIGHT - X
C
C
      REAL*4    SECNDS, X
C
C
      INTEGER*2 IHOUR, IMINUT, ISECON, IHUND
      REAL*4    RHOUR, RMINUT, RSECON, RHUND
      REAL*4    X1
C
      CALL GETTIM(IHOUR, IMINUT, ISECON, IHUND)
      RHOUR     =  FLOAT( IHOUR )
      RMINUT    =  FLOAT( IMINUT)
      RSECON    =  FLOAT( ISECON)
      RHUND     =  FLOAT( IHUND )
      X1        =  RHOUR*3600.0 + RMINUT*60.0 + RSECON +
     &             RHUND/100.0    
      SECNDS    =  X1 - X
C
      RETURN
      END