#define IDC_FRAME        256
#define IDC_INSTRUCT     201
#define IDC_EF_NAME      200
#define IDC_TEXTIN       220
#define IDC_EF_TEXTOUT   219
#define IDC_TERMINATE    218
#define IDC_INFO         217
#define IDC_PLAY         216
#define IDC_TEXT         215
#define IDC_SENDSONG     214
#define IDC_EF_SPEED     213
#define IDC_ERASENOTE    212
#define IDC_ERASEALL     211
#define IDC_PLAYBACK     210
#define IDC_SENDBITMAP   209
#define IDC_SELECT       208
#define IDC_SENDTEXT     207
#define IDC_EF_TEXT      206
#define IDD_GETNAME      108
#define IDD_LINK         107
#define IDD_GETSONG      106
#define IDD_GETBITMAP    105
#define IDD_GETTEXT      104
#define IDD_SENDSONG     103
#define IDD_SENDBITMAP   102
#define IDD_SENDTEXT     101
