#define ID_NULL         -1 
#define IDC_EF           1   
#define IDC_TEXT         2 
#define IDEF_APP         3 
#define IDEF_TOPIC       4 
#define IDEF_ITEM        5 
#define IDEF_DATA        6 
#define IDRB_ADVSTART    7
#define IDRB_ADVSTOP     8
#define IDRB_REQUEST     9 
#define IDRB_POKE       10 
#define IDRB_EXECUTE    11  
#define IDCBX_ASSYNC    20
#define IDC_DOIT        21
#define IDCB_QDATA      22
#define IDC_QFLUSH      23
#define IDC_QUPDATE     24
#define IDD_GETTIMEOUT  100
#define IDD_EXEC        101
