#define IDI_INIEDIT		    1
#define IDI_LIST		    5
#define IDM_SHOW		    10
#define IDM_EDIT		    11
#define IDM_SEARCH		    12
#define IDM_PRINT		    13
#define IDMI_SHOW_ALL		    100
#define IDMI_SHOW_APPNAMES	    101
#define IDMI_REFRESH		    102
#define IDMI_ABOUT		    103
#define IDMI_EDIT_ADD_APP	    200
#define IDMI_EDIT_ADD_KEY	    201
#define IDMI_EDIT_DELETE_APP	    202
#define IDMI_EDIT_DELETE_KEY	    203
#define IDMI_EDIT_CHANGE	    204
#define IDMI_PRINT_ALL		    300
#define IDMI_PRINT_APP		    301
#define IDDI_CHANGE_KEY_CANCEL	    555
#define IDDI_CHANGE_KEY_OK	    554
#define IDDI_CHANGE_KEY_TEXT_VAL    553
#define IDDI_CHANGE_KEY_TEXT_KEY    552
#define IDDI_CHANGE_KEY_TEXT_APP    551
#define IDD_CHANGE_KEY		    550
#define IDDI_DEL_APP_CANCEL	    544
#define IDDI_DEL_APP_OK 	    543
#define IDDI_DEL_APP_TEXT_APP	    541
#define IDD_DEL_APP		    540
#define IDDI_DEL_KEY_CANCEL	    534
#define IDDI_DEL_KEY_OK 	    533
#define IDDI_DEL_KEY_TEXT_APP	    532
#define IDDI_DEL_KEY_TEXT_KEY	    531
#define IDD_DEL_KEY		    530
#define IDDI_ADD_KEY_CANCEL	    525
#define IDDI_ADD_KEY_OK 	    524
#define IDDI_ADD_KEY_TEXT_VAL	    523
#define IDDI_ADD_KEY_TEXT_KEY	    522
#define IDDI_ADD_KEY_TEXT_APP	    521
#define IDD_ADD_KEY		    520
#define IDDI_ADD_APP_CANCEL	    513
#define IDDI_ADD_APP_OK 	    512
#define IDDI_ADD_APP_TEXT	    511
#define IDD_ADD_APP		    510
#define IDDI_SEARCH_CANCEL	    504
#define IDDI_SEARCH_NEXT	    503
#define IDDI_SEARCH_OK		    502
#define IDDI_SEARCH_TEXT	    501
#define IDD_SEARCH		    500
#define IDD_ABOUT		    600
#define IDDI_ABOUT_OK		    601
