#define FRAME_SEPARATE_BUTTONS   291
#define FRAME_FUNCTION_BUTTONS   290
#define FRAME_RESULT_AREA        289
#define TXT_RESULT_DISPLAY       288
#define BUTTON_CHANGE_SIGN       287
#define BUTTON_EQUALS            286
#define BUTTON_CLEAR             285
#define BUTTON_PER_CENT          284
#define BUTTON_SQUARE_ROOT       283
#define BUTTON_ADD               282
#define BUTTON_SUBTRACT          281
#define BUTTON_MULTIPLY          280
#define BUTTON_DIVIDE            279
#define BUTTON_DECIMAL_POINT     278
#define BUTTON_9                 277
#define BUTTON_8                 276
#define BUTTON_7                 275
#define BUTTON_6                 274
#define BUTTON_5                 273
#define BUTTON_4                 272
#define BUTTON_3                 271
#define BUTTON_2                 270
#define BUTTON_1                 269
#define BUTTON_0                 268
#define BUTTON_MMINUS            267
#define BUTTON_MPLUS             266
#define BUTTON_MR                265
#define BUTTON_MC                264
#define CALCDLG                  263
#define Calc                     0
#define CMD_ABOUT                260
#define CMD_EXIT                 259
#define CMD_PASTE                258
#define CMD_COPY                 257
#define IDB_SQR                  3
#define IDP_FINGER               2
#define IDR_CALC                 1
