PRINT READ.ME
PRINT TABCONT.TXT
PRINT INTRO.TXT
PRINT CHAP1.TXT
PRINT CHAP2.TXT
REM HIT ANY KEY WHEN THE PRINTER STOPS
PAUSE
PRINT CHAP3.TXT
PRINT CHAP4.TXT
PRINT CHAP5.TXT
PRINT CHAP6.TXT
REM HIT ANY KEY WHEN THE PRINTER STOPS
PAUSE
PRINT CHAP7.TXT
PRINT CHAP8.TXT
PRINT CHAP9.TXT
PRINT CHAP10.TXT
REM HIT ANY KEY WHEN THE PRINTER STOPS
PAUSE
PRINT CHAP11.TXT
PRINT CHAP12.TXT
PRINT CHAP13.TXT
PRINT CHAP14.TXT
